app/Http/routes.php
<?php

// Authentication routes...

Route::get('login', ['as' => 'login', 'uses' => 'Auth\AuthController@getLogin']);
Route::get('auth/login', ['as' => 'login', 'uses' => 'Auth\AuthController@getLogin']);
Route::post('auth/login', ['as' => 'login.store', 'uses' => 'Auth\AuthController@postLogin']);
Route::get('auth/logout', ['middleware' => 'auth', 'as' => 'logout', 'uses' => 'Auth\AuthController@getLogout']);

// Dashboard
Route::get('/dashboard', ['middleware' => 'auth', 'as' => 'login', 'uses' => 'AdminController@dashboard']);
Route::get('/{landing}', ['as' => 'landing.index', 'uses' => 'PageController@home']);
Route::post('/landing/{landing}', ['as' => 'landing.contact', 'uses' => 'PageController@contact']);
Route::post('/export', ['middleware' => 'auth', 'as' => 'export', 'uses' => 'AdminController@export']);

Route::get('/{landing}/send', ['as' => 'landing.send', 'uses' => 'PageController@send']);

// Landings
Route::group(['middleware' => 'auth'], function() {
    Route::resource('/dashboard/landing', 'LandingController');
});

// Missing
Route::get('/', 'PageController@any');
Route::get('{any}', 'PageController@any');

app/Landing.php
<?php

namespace Ean;

use Illuminate\Database\Eloquent\Model;

class Landing extends Model {

    protected $fillable = ['name', 'title', 'view'];

}

app/Http/Controllers/LandingController.php
<?php

namespace Ean\Http\Controllers;

use Ean\Http\Requests\StoreLandingPostRequest;
use Ean\Http\Requests\UpdateLandingPutRequest;
use Ean\Landing;
use Illuminate\Http\Request;

use Ean\Http\Requests;
use Ean\Http\Controllers\Controller;

class LandingController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $data['title'] = 'Landings';
        $data['landings'] = Landing::all();
        return view('landings.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $data['title'] = 'Crear Landing';
        return view('landings.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  StoreLandingPostRequest $request
     * @return Response
     */
    public function store(StoreLandingPostRequest $request)
    {
        $inputs = $request->only('name', 'title', 'view');
        Landing::create($inputs);
        return redirect()->route('dashboard.landing.index')->withMessage('Se creo nuevo landing');

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        $data['landing'] = Landing::find($id);
        $data['title'] = $data['landing']->title;
        return view('landings.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateLandingPutRequest $request
     * @param  int $id
     * @return Response
     */
    public function update(UpdateLandingPutRequest $request, $id)
    {
        $inputs = $request->only('name', 'title', 'view');
        Landing::updateOrCreate(['id' => $id], $inputs);
        return redirect()->route('dashboard.landing.index')->withMessage('Se actualizó el landing');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        $banner = Landing::find($id);
        $banner->delete();

        return redirect()->route('landing.index')->withMessage('Se eliminó el landing');
    }


}

resources/views/landings/create.blade.php
@extends('app')
@section('title', $title)
@section('content')
    <div class="container">

        @include('layouts.nav')

        @if($errors->any() or Session::has('errors'))
            <div class="alert alert-danger alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                <h4>Oh snap! You got an error!</h4>
                <ul>
                    @foreach ($errors->all(':message') as $message)
                        <li>{{ $message }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form method="POST" action="{{ URL::route('dashboard.landing.store') }}">

            {{ csrf_field() }}

            <div class="form-group">
                <label for="name">Nombre (URL): </label>
                <input type="text" id="name" name="name" class="form-control"/>
            </div>

            <div class="form-group">
                <label for="title">Titulo: </label>
                <input type="text" id="title" name="title" class="form-control"/>
            </div>

            <div class="form-group">
                <label for="view">Vista: </label>
                <input type="text" id="view" name="view" class="form-control"/>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Crear</button>
            </div>

        </form>

    </div>
@stop

resources/views/landings/edit.blade.php
@extends('app')
@section('title', $title)
@section('content')
    <div class="container">

        @include('layouts.nav')

        @if($errors->any() or Session::has('errors'))
            <div class="alert alert-danger alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                <h4>Oh snap! You got an error!</h4>
                <ul>
                    @foreach ($errors->all(':message') as $message)
                        <li>{{ $message }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form method="POST" action="{{ URL::route('dashboard.landing.update', $landing->id) }}">

            <input type="hidden" name="_method" value="PUT"/>
            {{ csrf_field() }}

            <div class="form-group">
                <label for="name">Nombre (URL):</label>
                <input type="text" id="name" name="name" class="form-control" value="{{ $landing->name }}"/>
            </div>

            <div class="form-group">
                <label for="title">Titulo: </label>
                <input type="text" id="title" name="title" class="form-control" value="{{ $landing->title }}"/>
            </div>

            <div class="form-group">
                <label for="view">Vista: </label>
                <input type="text" id="view" name="view" class="form-control" value="{{ $landing->view }}"/>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Actualizar</button>
            </div>

        </form>

    </div>
@stop

resources/views/landings/index.blade.php
@extends('app')
@section('title', $title)
@section('content')
    <div class="container">

        @include('layouts.nav')

        <a href="{{ URL::route('dashboard.landing.create') }}" class="btn btn-primary btn-block">Crear nuevo landing</a>

        <ul class="list-group">
            @forelse($landings as $landing)
                <a href="{{ URL::route('dashboard.landing.edit', $landing->id) }}" class="list-group-item">{{ $landing->title }}</a>
            @empty
            @endforelse
        </ul>

    </div>
@stop