app/Http/routes.php
<?php

// Authentication routes...

Route::get('login', ['as' => 'login', 'uses' => 'Auth\AuthController@getLogin']);
Route::get('auth/login', ['as' => 'login', 'uses' => 'Auth\AuthController@getLogin']);
Route::post('auth/login', ['as' => 'login.store', 'uses' => 'Auth\AuthController@postLogin']);
Route::get('auth/logout', ['middleware' => 'auth', 'as' => 'logout', 'uses' => 'Auth\AuthController@getLogout']);

// Dashboard
Route::get('/dashboard', ['middleware' => 'auth', 'as' => 'login', 'uses' => 'AdminController@dashboard']);
Route::get('/{landing}', ['as' => 'landing.index', 'uses' => 'PageController@home']);
Route::post('/landing/{landing}', ['as' => 'landing.contact', 'uses' => 'PageController@contact']);
Route::post('/export', ['middleware' => 'auth', 'as' => 'export', 'uses' => 'AdminController@export']);

Route::get('/{landing}/send', ['as' => 'landing.send', 'uses' => 'PageController@send']);

// Landings
Route::group(['middleware' => 'auth'], function() {
    Route::resource('/dashboard/landing', 'LandingController');
});

// Missing
Route::get('/', 'PageController@any');
Route::get('{any}', 'PageController@any');

resources/views/layouts/nav.blade.php
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/dashboard">Ean</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{{ URL::route('dashboard.landing.index') }}">Landings</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ Auth::user()->name }} <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ URL::route('logout') }}">Salir</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/notifications.blade.php
@if($errors->any() or Session::has('errors'))
    <div class="row nuper-bottom wow bounceInLeft text-danger">
        <div class="col-md-12">
            @foreach ($errors->all(':message') as $message)
                {{ $message }}
            @endforeach
        </div>
    </div>
@endif

@if(Session::has('message'))
    <div class="row nuper-bottom wow bounceInLeft">
        <div class="col-md-12">
            {{ Session::get('message') }}
        </div>
    </div>
@endif